package keywords

const (
	It = "it"

	Bool    = "__bool__"
	Number  = "__number__"
	Iter    = "__iter__"
	Next    = "__next__"
	Display = "__display__"
	Call    = "__call__"
	Slice   = "__slice__"
	Len     = "__length__"
	Dispose = "__dispose__"
	Clone   = "__clone__"

	Neg = "__neg__"
	Not = "__not__"
	Dec = "__dec__"
	Inc = "__inc__"

	Add   = "__add__"
	Sub   = "__sub__"
	Mul   = "__mul__"
	Div   = "__div__"
	Mod   = "__mod__"
	IDiv  = "__intdiv__"
	And   = "__and__"
	Or    = "__or__"
	Xor   = "__xor__"
	Shr   = "__shr__"
	Shl   = "__shl__"
	Eq    = "__eq__"
	Ne    = "__ne__"
	Gt    = "__gt__"
	Ge    = "__ge__"
	Lt    = "__lt__"
	Le    = "__le__"
	In    = "__in__"
	Index = "__index__"
	Bind  = "__bind__"
)
