name: Build Aqua
on:
    push:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                go: [1.24.2]
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: ${{ matrix.go }}
            - name: Build
              run: |
                  mkdir -p bin/${{ matrix.os }}
                  go build -o bin/${{ matrix.os }}/aqua aqua.go
            - name: Upload binaries
              uses: actions/upload-artifact@v3
              with:
                  name: aqua-${{ matrix.os }}
                  path: bin/${{ matrix.os }}/aqua
