name: Build & Release Aqua

on:
  release:
    types: [created]

permissions:
  contents: write  

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]

    steps:
      - uses: actions/checkout@v4

      - name: Set version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Building release version $VERSION"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.2

      - name: Build
        run: |
          EXT=""
          if [ "${{ matrix.os }}" = "windows" ]; then EXT=".exe"; fi
          mkdir -p bin/${{ matrix.os }}-${{ matrix.arch }}
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o bin/${{ matrix.os }}-${{ matrix.arch }}/aqua$EXT aqua.go

      - name: Zip binaries
        run: |
          cd bin
          zip -r ../aqua-${{ matrix.os }}-${{ matrix.arch }}.zip ./${{ matrix.os }}-${{ matrix.arch }}
          cd ..

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: aqua-${{ matrix.os }}-${{ matrix.arch }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}  